### ISSUE TITLE
Exercise 9 & 10

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/RubyTrack#9]
https://github.com/damilola-dealdey/RubyTrack/blob/master/Ex9-10/bin/main.rb

Question 9
Array - Hash
Create a method for Array that can create a hash having 'key' as length of the element and value as an array of all the elements of that length. Make use of for-in loop for the purpose. Eg:
['abc','def',1234,234,'abcd','x','mnop',5,'zZzZ'] -> {3=>["abc", "def", 234], 4=>[1234, "abcd", "mnop", "zZzZ"], 1=>["x", 5]}

Question 10
Hash - Inject
Write a method that groups the above hash into 2 groups of 'even' and 'odd' length using 'inject'.Eg:
['abc','def',1234,234,'abcd','x','mnop',5,'zZzZ'] -> {odd: [["x", 5], ["abc", "def", 234]], even: [[1234, "abcd", "mnop", "zZzZ"]]}

**Comment by segunadeleye** [comment]
Question 10
1. `group_hash` should not be in main.rb
2. Use symbols for the hash keys.

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
1. For `Fixnum#parity`, `self` is not required.
2. Why is `group_hash` not in the `Array` class.
3. Even for the second grouping, the method has to be called on the array. For example
`['abc','def',1234,234,'abcd','x','mnop',5,'zZzZ'].group_by_parity`

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
Looks good.
